In [59]:
#install packages
!pip install pandas numpy mlxtend openpyxl

Requirement already satisfied: pandas in c:\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\python314\lib\site-packages (2.4.3)
Requirement already satisfied: mlxtend in c:\python314\lib\site-packages (0.24.0)
Requirement already satisfied: openpyxl in c:\python314\lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.16.3 in c:\python314\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\python314\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\python314\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in c:\python314\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: et-xmlfile in c:\python314\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\python314\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\python314\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
#import libraries
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [8]:
dataset = pd.read_excel('Egyptian_Grocery_Transactions.xlsx',header=None)
dataset

                                     0
0                          سكر,لبن,شاي
1                           فراخ,بطاطس
2                              رز,فراخ
3                    عسل,لحمة,رز,زبادي
4                           بصل,رز,عدس
5                شيبسي,فلفل,بيبسي,مياه
6                     فراخ,بطاطس,شيبسي
7                 طماطم,عدس,كورن فليكس
8                عسل,مربة,زيت,عيش بلدي
9        فراخ,مكرونة,شاي,كشري,سكر,سمنة
10                             عسل,عدس
11   زيت,بيض,فول,مكرونة,صلصة,جبنة قريش
12           شاي,عدس,عسل,زيت,بيبسي,بيض
13                         رز,عدس,كشري
14                       كشري,عيش بلدي
15                      لبن,بيبسي,مربة
16                 سكر,عيش بلدي,مكرونة
17                   بيبسي,زبادي,طعمية
18           بيبسي,سكر,زيت,عدس,فول,بيض
19  بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش

In [9]:
dataset.shape

(20, 1)

In [12]:
dataset.columns = ['Items']
dataset

                                 Items
0                          سكر,لبن,شاي
1                           فراخ,بطاطس
2                              رز,فراخ
3                    عسل,لحمة,رز,زبادي
4                           بصل,رز,عدس
5                شيبسي,فلفل,بيبسي,مياه
6                     فراخ,بطاطس,شيبسي
7                 طماطم,عدس,كورن فليكس
8                عسل,مربة,زيت,عيش بلدي
9        فراخ,مكرونة,شاي,كشري,سكر,سمنة
10                             عسل,عدس
11   زيت,بيض,فول,مكرونة,صلصة,جبنة قريش
12           شاي,عدس,عسل,زيت,بيبسي,بيض
13                         رز,عدس,كشري
14                       كشري,عيش بلدي
15                      لبن,بيبسي,مربة
16                 سكر,عيش بلدي,مكرونة
17                   بيبسي,زبادي,طعمية
18           بيبسي,سكر,زيت,عدس,فول,بيض
19  بيض,بيبسي,طعمية,سكر,سمنة,جبنة قريش

In [19]:
transactions = []
items = dataset['Items'].values
for i in range (0, len(items)):
    transactions.append(items[i].split(","))

transactions

[['سكر', 'لبن', 'شاي'],
 ['فراخ', 'بطاطس'],
 ['رز', 'فراخ'],
 ['عسل', 'لحمة', 'رز', 'زبادي'],
 ['بصل', 'رز', 'عدس'],
 ['شيبسي', 'فلفل', 'بيبسي', 'مياه'],
 ['فراخ', 'بطاطس', 'شيبسي'],
 ['طماطم', 'عدس', 'كورن فليكس'],
 ['عسل', 'مربة', 'زيت', 'عيش بلدي'],
 ['فراخ', 'مكرونة', 'شاي', 'كشري', 'سكر', 'سمنة'],
 ['عسل', 'عدس'],
 ['زيت', 'بيض', 'فول', 'مكرونة', 'صلصة', 'جبنة قريش'],
 ['شاي', 'عدس', 'عسل', 'زيت', 'بيبسي', 'بيض'],
 ['رز', 'عدس', 'كشري'],
 ['كشري', 'عيش بلدي'],
 ['لبن', 'بيبسي', 'مربة'],
 ['سكر', 'عيش بلدي', 'مكرونة'],
 ['بيبسي', 'زبادي', 'طعمية'],
 ['بيبسي', 'سكر', 'زيت', 'عدس', 'فول', 'بيض'],
 ['بيض', 'بيبسي', 'طعمية', 'سكر', 'سمنة', 'جبنة قريش']]

In [27]:
encoder = TransactionEncoder()
transactionsEncoded = encoder.fit(transactions).transform(transactions)
transactionsEncoded = pd.DataFrame(data = transactionsEncoded, columns=encoder.columns_, dtype=int)
transactionsEncoded

,بصل,بطاطس,بيبسي,بيض,جبنة قريش,رز,زبادي,زيت,سكر,سمنة,...,فراخ,فلفل,فول,كشري,كورن فليكس,لبن,لحمة,مربة,مكرونة,مياه
0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
6,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
8,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
9,0,0,0,0,0,0,0,0,1,1,...,1,0,0,1,0,0,0,0,1,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,1,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,1,0
12,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
16,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
17,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,1,1,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,0
19,0,0,1,1,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [58]:
support = apriori(transactionsEncoded, min_support=0.1, use_colnames=True)
support.sort_values(by = 'support')

C:\Python314\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support                           itemsets
0      0.10                 frozenset({بطاطس})
3      0.10             frozenset({جبنة قريش})
5      0.10                 frozenset({زبادي})
8      0.10                  frozenset({سمنة})
10     0.10                 frozenset({شيبسي})
11     0.10                 frozenset({طعمية})
30     0.10              frozenset({بيض, عدس})
29     0.10              frozenset({بيض, سكر})
24     0.10            frozenset({سكر, بيبسي})
25     0.10          frozenset({طعمية, بيبسي})
26     0.10            frozenset({عدس, بيبسي})
23     0.10            frozenset({زيت, بيبسي})
21     0.10           frozenset({فراخ, بطاطس})
19     0.10                  frozenset({مربة})
18     0.10                   frozenset({لبن})
16     0.10                   frozenset({فول})
31     0.10              frozenset({فول, بيض})
27     0.10        frozenset({بيض, جبنة قريش})
45     0.10         frozenset({فول, بيض, زيت})
44     0.10         frozenset({زيت, بيض, عدس})
43     0.10       frozenset({زيت, عدس, بيبسي})
42     0.10       frozenset({عدس, بيض, بيبسي})
41     0.10       frozenset({بيض, سكر, بيبسي})
40     0.10       frozenset({زيت, بيض, بيبسي})
39     0.10              frozenset({عدس, عسل})
38     0.10           frozenset({مكرونة, سكر})
37     0.10              frozenset({شاي, سكر})
36     0.10             frozenset({سمنة, سكر})
35     0.10              frozenset({فول, زيت})
34     0.10              frozenset({زيت, عسل})
33     0.10              frozenset({زيت, عدس})
32     0.10               frozenset({عدس, رز})
46     0.10  frozenset({زيت, عدس, بيض, بيبسي})
17     0.15                  frozenset({كشري})
28     0.15              frozenset({زيت, بيض})
22     0.15            frozenset({بيض, بيبسي})
9      0.15                   frozenset({شاي})
14     0.15              frozenset({عيش بلدي})
20     0.15                frozenset({مكرونة})
6      0.20                   frozenset({زيت})
15     0.20                  frozenset({فراخ})
13     0.20                   frozenset({عسل})
4      0.20                    frozenset({رز})
2      0.20                   frozenset({بيض})
7      0.25                   frozenset({سكر})
12     0.30                   frozenset({عدس})
1      0.30                 frozenset({بيبسي})

In [57]:
AnalysisData = association_rules(support, metric='confidence', min_threshold=0.3)
AnalysisData[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by = 'lift')

#There is no weak rules and all rules with lift greater than 1 is strong rule

,antecedents,consequents,support,confidence,lift
10,frozenset({بيبسي}),frozenset({عدس}),0.1,0.333333,1.111111
11,frozenset({عدس}),frozenset({بيبسي}),0.1,0.333333,1.111111
6,frozenset({سكر}),frozenset({بيبسي}),0.1,0.400000,1.333333
7,frozenset({بيبسي}),frozenset({سكر}),0.1,0.333333,1.333333
4,frozenset({زيت}),frozenset({بيبسي}),0.1,0.500000,1.666667
...,...,...,...,...,...
71,frozenset({فول}),"frozenset({زيت, بيض})",0.1,1.000000,6.666667
80,"frozenset({زيت, عدس})","frozenset({بيض, بيبسي})",0.1,1.000000,6.666667
82,"frozenset({عدس, بيبسي})","frozenset({زيت, بيض})",0.1,1.000000,6.666667
78,"frozenset({زيت, بيبسي})","frozenset({بيض, عدس})",0.1,1.000000,10.000000
83,"frozenset({بيض, عدس})","frozenset({زيت, بيبسي})",0.1,1.000000,10.000000